name: Deploy to server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Vérifier le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2: Installer sshpass
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    # Étape 3: Git Pull
    - name: Run Git Pull on server
      run: |
        sshpass -p 'aspnet-site' ssh -o StrictHostKeyChecking=no aspnet-site@skyserver.fr 'cd aspnet-site && git config --global --add safe.directory /home/aspnet-site/aspnet-site && git pull origin main'

    # Étape 4: Exécuter des commandes via sshpass et SSH
    - name: Run SSH command
      run: |
        sshpass -p 'aspnet-site' ssh aspnet-site@skyserver.fr 'docker compose restart --force-recreate'
